# Escala en base a la cantidad de solicitudes http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-video-playback
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-playback
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: pbbase
          selector:
            matchLabels:
              host: multimediakind.ddns.net
        target:
          type: AverageValue
          averageValue: 100m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-video-playback-videotest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-playback-videotest
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: pbvideotest
          selector:
            matchLabels:
              host: playback.videotest.sitrack.io
        target:
          type: AverageValue
          averageValue: 100m


# Escala en base a la cantidad de conexiones simultaneas TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-video-playback-tcp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-playback
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: pbtcpbase
          selector:
            matchLabels:
              entrypoint: pbtcp
        target:
          type: AverageValue
          averageValue: 4000m # 4 conexiones maximas TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-video-playback-videotest-tcp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-playback-videotest
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: pbtcpvideotest
          selector:
            matchLabels:
              entrypoint: pbtcpvideotest
        target:
          type: AverageValue
          averageValue: 4000m # 4 conexiones maximas TCP