---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-doug-tcp
  namespace: beta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doug-tcp
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: dgtcpbase
          selector:
            matchLabels:
              entrypoint: dgtcp
        target:
          type: AverageValue
          averageValue: 4000m # 4 conexiones maximas TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-doug-tcp-videotest
  namespace: beta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doug-tcp-videotest
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: dgtcpvideotest
          selector:
            matchLabels:
              entrypoint: dgtcpvideotest
        target:
          type: AverageValue
          averageValue: 4000m # 4 conexiones maximas TCP