apiVersion: v1
kind: Service
metadata:
  name: doug-tcp
  namespace: beta
spec:
  selector:
    app: doug-tcp
  ports:
    - protocol: TCP
      port: 12094
      targetPort: 9000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: doug-tcp-videotest
  namespace: beta
spec:
  selector:
    app: doug-tcp-videotest
  ports:
    - protocol: TCP
      port: 12094
      targetPort: 9000
  type: NodePort